export const API_PREFIX = "/api/v1";

export const endpoints = {
  health: `${API_PREFIX}/health`,
  auth: `${API_PREFIX}/auth`,
  iamUsers: `${API_PREFIX}/iam/users`,
  iamRoles: `${API_PREFIX}/iam/roles`,
  iamPermissions: `${API_PREFIX}/iam/permissions`,
  catalogBrands: `${API_PREFIX}/catalog/brands`,
  catalogCategories: `${API_PREFIX}/catalog/categories`,
  catalogSettings: `${API_PREFIX}/catalog/settings`,
  products: `${API_PREFIX}/products`,
  media: `${API_PREFIX}/media`,
  consignments: `${API_PREFIX}/consignments`,
  orders: `${API_PREFIX}/orders`,
  vouchers: `${API_PREFIX}/vouchers`,
  cart: `${API_PREFIX}/cart`,
  wishlist: `${API_PREFIX}/wishlist`,
  wallets: `${API_PREFIX}/financial/wallets`,
  withdrawals: `${API_PREFIX}/financial/withdrawals`,
  notifications: `${API_PREFIX}/notifications`,
  auditActivityLogs: `${API_PREFIX}/audit/activity-logs`,
  analytics: `${API_PREFIX}/analytics`,
  conversations: `${API_PREFIX}/conversations`,
} as const;
